apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-toml-configmap
  namespace: ingress-traefik
data:
  traefik.toml: |
    #[global]
    #
    [accessLog] 

    [serversTransport]
    # Do not verify backend certificates (use https backends)
      insecureSkipVerify = true
    
    [entryPoints]
      [entryPoints.web]
        address = ":80"
        #compress = true
      [entryPoints.websecure]
        address = ":443"
        [entryPoints.websecure.forwardedHeaders]
          insecure = true
      [entryPoint.traefik]
        address = ":8080"
    
    [api]
      insecure = true
      dashboard = true
      debug = true
    
    [log]
      level = "DEBUG"
    
    [providers]
      [providers.file]
        filename = "/etc/traefik/dynamic.toml"
        watch = "true"
      [providers.kubernetesingress]