apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-service
  namespace: ingress-traefik
  labels:
    k8s-app: traefik-ingress-lb
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30800
      name: http
    - port: 443
      nodePort: 30043
      name: https
    - port: 8080
      nodePort: 30880
      name: admin
  selector:
    k8s-app: traefik-ingress-lb