---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: ansible-awx
spec:
  deployment_type: awx
  tower_admin_user: toweradmin
  tower_admin_email: dgowran@gmail.com
  tower_admin_password: tower2020!
  tower_broadcast_websocket_secret: tower2020!
  tower_postgres_storage_class: local-storage
  tower_service_type: node
